services:
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: warehouse
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./scripts:/docker-entrypoint-initdb.d
      - ./data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8085:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - pgdatabase

volumes:
  pgdata:
  pgadmin_data: